### ISSUE TITLE
Functions returning NoneType

### ISSUE THREAD

**Issue by Hamilwicke** [linusg/rpi-backlight#9]
I'm getting the following error. 

Ill note that I'm not using an 'official' rpi screen. if that matters. I'm using a 7" touch via hdmi

`pi@raspberrypi:~ $ sudo python3`

Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.`

`>>> import rpi_backlight as bl`
`>>> bl.set_brightness(255)`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/rpi_backlight-1.8.1-py3.5.egg/rpi_backlight.py", line 83, in set_brightness
  File "/usr/local/lib/python3.5/dist-packages/rpi_backlight-1.8.1-py3.5.egg/rpi_backlight.py", line 62, in get_max_brightness
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by linusg** [comment]
> Ill note that I'm not using an 'official' rpi screen. if that matters. I'm using a 7" touch via hdmi

Well of course that matters! Quoting the README, emphasis mine:

> A Python module for controlling power and brightness of the **official Raspberry Pi 7" touch display**

This module depends on the driver for the display creating certain files in the sysfs, find details in the source code.

You cannot use this for any arbitrary 7" display and expect things to work. Look at the documentation of yours to find a way of controlling the brightness, if any. I believe it's not possible, because it's HDMI. But that's up to you.
